### ISSUE TITLE
The "APK not created try later" error occurring while generating new APK

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#593] opened 2021-03-19 05:26 UTC
Ref: https://secure.helpscout.net/conversation/1376491872/171841?folderId=2770545

Screenshot: https://prnt.sc/10plybt

When the user is going to create the new APK, he is getting the error message "APK not created try later". The issue is only at user's end.

**Comment by ajeetku** [comment] 2021-03-27 08:40
Closing, The issue is resolved on the user site.

**Closed by ajeetku** 2021-03-27 08:40 UTC
