### ISSUE TITLE
Page auto refresh on IOS when using in wpDataTable plugin

### ISSUE THREAD

**Issue by hafizul-hackathon** [ahmedkaludi/pwa-for-wp#563] opened 2020-12-25 21:04 UTC
I have a bootstrap datatable and when opened in IOS with PWA, the page refreshes when I go to next page or when I click Page 2,3... please advice how to fix this. Thanks..

**Comment by ajeetku** [comment] 2021-01-13 10:13
@hafizul-hackathon  The issue is not created on our site, please provide some more details to recreate it

**Comment by hafizul-hackathon** [comment] 2021-01-18 17:33
ajeetku,

This happens when I open a page with tables generated by plugin wpDataTables. To replicate this, please do this:
1. install wpDataTables plugin in your wordpress.
2. create any simple table with more than 10 records / lines.
3. click page 2,3 or next page.
This is when the **bugs** happened. The page will auto refresh and back to page 1. You **cant** go to next page, cant filter and cant change maximum records per page. It will always refresh to original page.
When I open the same table outside PWA, it works just fine. So I highly suspect PWA is the one caused it.
Please help.

**Comment by ajeetku** [comment] 2021-02-26 09:23
@hafizul-hackathon please contact once on https://pwa-for-wp.com/contact-us/

**Comment by ajeetku** [comment] 2021-03-01 05:36
Closing this ticket, for now, will open when issue is re-occurred

**Closed by ajeetku** 2021-03-01 05:36 UTC
Labels: High Priority, bug
