### ISSUE TITLE
If the Offline Google analytics option in the PWA option panel then showing workbox console error showing

### ISSUE THREAD

**Issue by akashagrjsr** [ahmedkaludi/pwa-for-wp#524] opened 2020-09-14 13:55 UTC
Screenshot: https://prnt.sc/uh2f6z

Ref: https://secure.helpscout.net/conversation/1251806260/147939?folderId=2770545

**Comment by ajeetku** [comment] 2020-10-08 09:45
This issue occurs because of adblocker, that's the cause of the whole service worker is blocked. Added fix to avoid the error.

**Comment by ajeetku** [comment] 2020-10-12 08:40
Fix applied 
released in current version 1.7.22

**Closed by ajeetku** 2020-10-12 08:40 UTC
Labels: High Priority, bug
